{"name": "test_DB_link", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nBacktrace:\n\t(No symbol) [0x00BAF243]\n\t(No symbol) [0x00B37FD1]\n\t(No symbol) [0x00A2D04D]\n\t(No symbol) [0x00A5C0B0]\n\t(No symbol) [0x00A5C22B]\n\t(No symbol) [0x00A8E612]\n\t(No symbol) [0x00A785D4]\n\t(No symbol) [0x00A8C9EB]\n\t(No symbol) [0x00A78386]\n\t(No symbol) [0x00A5163C]\n\t(No symbol) [0x00A5269D]\n\tGetHandleVerifier [0x00E49A22+2655074]\n\tGetHandleVerifier [0x00E3CA24+2601828]\n\tGetHandleVerifier [0x00C58C0A+619850]\n\tGetHandleVerifier [0x00C57830+614768]\n\t(No symbol) [0x00B405FC]\n\t(No symbol) [0x00B45968]\n\t(No symbol) [0x00B45A55]\n\t(No symbol) [0x00B5051B]\n\tBaseThreadInitThunk [0x7584FEF9+25]\n\tRtlGetAppContainerNamedObjectPath [0x76F27BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x76F27B8E+238]", "trace": "@allure.story('確認驗證碼能是否正常/並且確認')\n    @pytest.mark.run(order=7)\n    def test_DB_link():\n     time.sleep(5)\n     conn = pymysql.connect(**db_setting)\n     with conn.cursor() as cursor:\n    \n        command =\"select code From telligent_member.member_captcha ORDER BY expired_time desc LIMIT 1;\"\n        cursor.execute(command)\n        result =cursor.fetchone()\n        print(result)\n>    WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, \"/html/body/div[1]/div/div/main/div/div[2]/div/div/div/form/div/label/div/div[1]/div/input\")))\n\nSSO_Line_test.py:92: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"0f654423b1d35872ec48348e5d231b16\")>, method = <function presence_of_element_located.<locals>._predicate at 0x000002252A323910>, message = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       Backtrace:\nE       \t(No symbol) [0x00BAF243]\nE       \t(No symbol) [0x00B37FD1]\nE       \t(No symbol) [0x00A2D04D]\nE       \t(No symbol) [0x00A5C0B0]\nE       \t(No symbol) [0x00A5C22B]\nE       \t(No symbol) [0x00A8E612]\nE       \t(No symbol) [0x00A785D4]\nE       \t(No symbol) [0x00A8C9EB]\nE       \t(No symbol) [0x00A78386]\nE       \t(No symbol) [0x00A5163C]\nE       \t(No symbol) [0x00A5269D]\nE       \tGetHandleVerifier [0x00E49A22+2655074]\nE       \tGetHandleVerifier [0x00E3CA24+2601828]\nE       \tGetHandleVerifier [0x00C58C0A+619850]\nE       \tGetHandleVerifier [0x00C57830+614768]\nE       \t(No symbol) [0x00B405FC]\nE       \t(No symbol) [0x00B45968]\nE       \t(No symbol) [0x00B45A55]\nE       \t(No symbol) [0x00B5051B]\nE       \tBaseThreadInitThunk [0x7584FEF9+25]\nE       \tRtlGetAppContainerNamedObjectPath [0x76F27BBE+286]\nE       \tRtlGetAppContainerNamedObjectPath [0x76F27B8E+238]\n\n..\\..\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:95: TimeoutException"}, "attachments": [{"name": "stdout", "source": "53ab72ec-17fc-40c8-9bc1-22d79180ba57-attachment.txt", "type": "text/plain"}], "start": 1669949725436, "stop": 1669949740747, "uuid": "d893f17c-393c-4630-bbe9-bdda922e7c12", "historyId": "85528444a32638a2e3664690277399f4", "testCaseId": "eb2c479fdd59ca25da8d47312f8f3f94", "fullName": "SSO_Line_test#test_DB_link", "labels": [{"name": "story", "value": "確認驗證碼能是否正常/並且確認"}, {"name": "tag", "value": "run(order=7)"}, {"name": "suite", "value": "SSO_Line_test"}, {"name": "host", "value": "C010700042"}, {"name": "thread", "value": "22564-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "SSO_Line_test"}]}